src/Entity/MethodePaiment.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\MethodePaimentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MethodePaimentRepository::class)
 */
class MethodePaiment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * 
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 1,
     *      max = 20,
     *      minMessage = "elle doit avoir {{ limit }} chiffres",
     *      maxMessage = "elle doit avoir {{ limit }} chiffres")
     */
    private $methode;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 1,
     *      max = 20,
     *      minMessage = "elle doit avoir {{ limit }} chiffres",
     *      maxMessage = "elle doit avoir {{ limit }} chiffres")
     */
    private $type_paiment;

    /**
     * @ORM\OneToOne(targetEntity=Facture::class, mappedBy="paiment", cascade={"persist", "remove"})
     */
    private $facture;
/**
 * @return int
 */
    public function getId(): ?int
    {
        return $this->id;
    }
/**
 * @return string
 */
    public function getMethode(): ?string
    {
        return $this->methode;
    }
/**
 * @param string $methode
 * @return MethodePaiment
 */
    public function setMethode(string $methode): self
    {
        $this->methode = $methode;

        return $this;
    }
/**
 * @return string
 */
    public function getTypePaiment(): ?string
    {
        return $this->type_paiment;
    }
/**
 * @param string $type_paiment
 * @return MethodePaiment
 */
    public function setTypePaiment(string $type_paiment): self
    {
        $this->type_paiment = $type_paiment;

        return $this;
    }
public function __toString(){
    return $this->methode;
}
    public function getFacture(): ?Facture
    {
        return $this->facture;
    }

    public function setFacture(?Facture $facture): self
    {
        // unset the owning side of the relation if necessary
        if ($facture === null && $this->facture !== null) {
            $this->facture->setPaiment(null);
        }

        // set the owning side of the relation if necessary
        if ($facture !== null && $facture->getPaiment() !== $this) {
            $facture->setPaiment($this);
        }

        $this->facture = $facture;

        return $this;
    }
}

src/Form/MethodePaimentType.php
<?php

namespace App\Form;

use App\Entity\MethodePaiment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MethodePaimentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('methode')
            ->add('type_paiment')
            ->add('facture')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MethodePaiment::class,
        ]);
    }
}

src/Controller/MethodePaimentController.php
<?php

namespace App\Controller;

use App\Entity\MethodePaiment;
use App\Form\MethodePaimentType;
use App\Repository\MethodePaimentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

/**
 * @Route("/methode/paiment")
 */
class MethodePaimentController extends AbstractController
{
    /**
     * @Route("/", name="methode_paiment_index", methods={"GET"})
     */
    public function index(MethodePaimentRepository $methodePaimentRepository, ChartBuilderInterface $chartBuilder): Response
    {
        $chart = $chartBuilder->createChart(Chart::TYPE_LINE);
        $chart->setData([
            'labels' => ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            'datasets' => [
                [
                    'label' => 'My First dataset',
                    'backgroundColor' => 'rgb(255, 99, 132)',
                    'borderColor' => 'rgb(255, 99, 132)',
                    'data' => [0, 10, 5, 2, 20, 30, 45],
                ],
            ],
        ]);

        $chart->setOptions([
            'scales' => [
                'yAxes' => [
                    ['ticks' => ['min' => 0, 'max' => 100]],
                ],
            ],
        ]);
        return $this->render('methode_paiment/index.html.twig', [
            'methode_paiments' => $methodePaimentRepository->findAll(),
            'chart' => $chart,
        ]);
    }

    /**
     * @Route("/new", name="methode_paiment_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $methodePaiment = new MethodePaiment();
        $form = $this->createForm(MethodePaimentType::class, $methodePaiment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($methodePaiment);
            $entityManager->flush();

            return $this->redirectToRoute('methode_paiment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('methode_paiment/new.html.twig', [
            'methode_paiment' => $methodePaiment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="methode_paiment_show", methods={"GET"})
     */
    public function show(MethodePaiment $methodePaiment): Response
    {
        return $this->render('methode_paiment/show.html.twig', [
            'methode_paiment' => $methodePaiment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="methode_paiment_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, MethodePaiment $methodePaiment, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MethodePaimentType::class, $methodePaiment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('methode_paiment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('methode_paiment/edit.html.twig', [
            'methode_paiment' => $methodePaiment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="methode_paiment_delete", methods={"POST"})
     */
    public function delete(Request $request, MethodePaiment $methodePaiment, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$methodePaiment->getId(), $request->request->get('_token'))) {
            $entityManager->remove($methodePaiment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('methode_paiment_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/", name="chart")
     */
    public function chart(ChartBuilderInterface $chartBuilder): Response
    {
        $chart = $chartBuilder->createChart(Chart::TYPE_LINE);
        $chart->setData([
            'labels' => ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            'datasets' => [
                [
                    'label' => 'My First dataset',
                    'backgroundColor' => 'rgb(255, 99, 132)',
                    'borderColor' => 'rgb(255, 99, 132)',
                    'data' => [0, 10, 5, 2, 20, 30, 45],
                ],
            ],
        ]);

        $chart->setOptions([
            'scales' => [
                'yAxes' => [
                    ['ticks' => ['min' => 0, 'max' => 100]],
                ],
            ],
        ]);

        return $this->render('methode_paiment/chart.html.twig', [
            'chart' => $chart,
        ]);
    }


}

templates/methode_paiment/_delete_form.html.twig
<form method="post" action="{{ path('methode_paiment_delete', {'id': methode_paiment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ methode_paiment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/methode_paiment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/methode_paiment/chart.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}MethodePaiment index{% endblock %}

{% block body %}
    <h1>Chart</h1>

{{ render_chart(chart) }}

{% endblock %}

templates/methode_paiment/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Edit MethodePaiment{% endblock %}

{% block body %}
    <h1>Edit MethodePaiment</h1>

    {{ include('methode_paiment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('methode_paiment_index') }}">back to list</a>

    {{ include('methode_paiment/_delete_form.html.twig') }}
{% endblock %}

templates/methode_paiment/index.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}MethodePaiment index{% endblock %}

{% block body %}
    <h1>MethodePaiment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Methode</th>
                <th>Type_paiment</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for methode_paiment in methode_paiments %}
            <tr>
                <td>{{ methode_paiment.id }}</td>
                <td>{{ methode_paiment.methode }}</td>
                <td>{{ methode_paiment.typePaiment }}</td>
                <td>
                    <a href="{{ path('methode_paiment_show', {'id': methode_paiment.id}) }}">show</a>
                    <a href="{{ path('methode_paiment_edit', {'id': methode_paiment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('methode_paiment_new') }}">Create new</a>
<br>
Chart :
<br>
{{ render_chart(chart) }}
{% endblock %}

templates/methode_paiment/new.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}New MethodePaiment{% endblock %}

{% block body %}
    <h1>Create new MethodePaiment</h1>

    {{ include('methode_paiment/_form.html.twig') }}

    <a href="{{ path('methode_paiment_index') }}">back to list</a>
{% endblock %}

templates/methode_paiment/show.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}MethodePaiment{% endblock %}

{% block body %}
    <h1>MethodePaiment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ methode_paiment.id }}</td>
            </tr>
            <tr>
                <th>Methode</th>
                <td>{{ methode_paiment.methode }}</td>
            </tr>
            <tr>
                <th>Type_paiment</th>
                <td>{{ methode_paiment.typePaiment }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('methode_paiment_index') }}">back to list</a>

    <a href="{{ path('methode_paiment_edit', {'id': methode_paiment.id}) }}">edit</a>

    {{ include('methode_paiment/_delete_form.html.twig') }}
{% endblock %}