src/Entity/Facture.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\FactureRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FactureRepository::class)
 */
class Facture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * * @Assert\NotBlank
     */
    private $nom_user;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $prenom_user;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank
     *  @Assert\Length(
     *      min = 5,
     *      max = 7,
     *      minMessage = "Matricule doit avoir {{ limit }} chiffres",
     *      maxMessage = "Matricule doit avoir {{ limit }} chiffres")
     */
    private $matricule;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank
     *  @Assert\Length(
     *      min = 1,
     *      max = 8,
     *      minMessage = "Code doit avoir {{ limit }} chiffres",
     *      maxMessage = "Code doit avoir {{ limit }} chiffres")
     *
     */
    private $code;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Positive
     */
    private $prix;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank
     */
    private $date_fin;

    /**
     * @ORM\OneToOne(targetEntity=MethodePaiment::class, inversedBy="facture", cascade={"persist", "remove"})
     */
    private $paiment;
/**
 * @return integer
 */
    public function getId(): ?int
    {
        return $this->id;
    }
/**
 * @return string
 */
    public function getNomUser(): ?string
    {
        return $this->nom_user;
    }
/**
 * @param string $nom_user
 * @return Facture
 */
    public function setNomUser(string $nom_user): self
    {
        $this->nom_user = $nom_user;

        return $this;
    }
/**
 *@return string
 */
    public function getPrenomUser(): ?string
    {
        return $this->prenom_user;
    }
/**
 *@param string $prenom_user
  * @return Facture
 */
    public function setPrenomUser(string $prenom_user): self
    {
        $this->prenom_user = $prenom_user;

        return $this;
    }
/**
 * @return string
 */
    public function getMatricule(): ?string
    {
        return $this->matricule;
    }
/**
 * @param string $Matricule
  * @return Facture
 */
    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }
/**
 * @return string
 */
    public function getCode(): ?string
    {
        return $this->code;
    }
/**
 * @param string $code
 * @return Facture
 */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }
/**
 * @return int
 */
    public function getPrix(): ?int
    {
        return $this->prix;
    }
/**
 * @param int $prix
 *  @return Facture
 */
    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
/**
 * @return date
 */
    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }
/**
 * @param date $date_debut
 * @return Facture
 */
    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }
/**
 * @return date
 */
    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }
/**
 * @param date $date_fin
 * @return Facture
 */
    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }
public function __toString(){
    return $this->code;
}
    public function getPaiment(): ?MethodePaiment
    {
        return $this->paiment;
    }

    public function setPaiment(?MethodePaiment $paiment): self
    {
        $this->paiment = $paiment;

        return $this;
    }
}

src/Form/FactureType.php
<?php

namespace App\Form;

use App\Entity\Facture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FactureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_user')
            ->add('prenom_user')
            ->add('matricule')
            ->add('code')
            ->add('prix')
            ->add('date_debut')
            ->add('date_fin')
            ->add('paiment')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Facture::class,
        ]);
    }
}

src/Controller/FactureController.php
<?php

namespace App\Controller;

use App\Entity\Facture;
use App\Form\FactureType;
use App\Repository\FactureRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

/**
 * @Route("/facture")
 */
class FactureController extends AbstractController
{

    /**
     * @Route("/", name="facture_index", methods={"GET"})
     */
    public function index(Request $request, PaginatorInterface $paginator): Response
    {

        // Retrieve the entity manager of Doctrine
        $em = $this->getDoctrine()->getManager();
        
        // Get some repository of data, in our case we have an Appointments entity
        $factureRepository = $em->getRepository(Facture::class);
                        
        // Find all the data on the Appointments table, filter your query as you need
        $query = $factureRepository->createQueryBuilder('p')
        ->getQuery();

        $pagination = $paginator->paginate(
            $query, 
            $request->query->getInt('page', 1), 
            3 
        );
    
        // parameters to template
        return $this->render('facture/index.html.twig', ['factures' => $pagination]);
    }

    /**
     * @Route("/new", name="facture_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $facture = new Facture();
        $form = $this->createForm(FactureType::class, $facture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($facture);
            $entityManager->flush();

            return $this->redirectToRoute('facture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('facture/new.html.twig', [
            'facture' => $facture,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="facture_show", methods={"GET"})
     */
    public function show(Facture $facture): Response
    {
        return $this->render('facture/show.html.twig', [
            'facture' => $facture,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="facture_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Facture $facture, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FactureType::class, $facture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('facture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('facture/edit.html.twig', [
            'facture' => $facture,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="facture_delete", methods={"POST"})
     */
    public function delete(Request $request, Facture $facture, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$facture->getId(), $request->request->get('_token'))) {
            $entityManager->remove($facture);
            $entityManager->flush();
        }

        return $this->redirectToRoute('facture_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("", name="facture_pdf", methods={"POST"})
     */
    public function pdfAction()
    {
        $knpSnappyPdf->generateFromHtml(
        $this->render('facture/index.html.twig', [
            'factures' => $factureRepository->findAll(),
        ]),
        'D:\xampp\htdocs\azizpi\var\cache\dev\snappy\file.pdf'
         );
         
        $html = $this->render('facture/index.html.twig', [
            'factures' => $factureRepository->findAll(),
        ]);

        return new PdfResponse(
            $knpSnappyPdf->getOutputFromHtml($html),
            'file.pdf'
        );
    }


    
    /**
     * @Route("search", name="ajax_search", methods={"GET"})
     */
        public function searchAction(Request $request)
        {
            $em = $this->getDoctrine()->getManager();
      
            $requestString = $request->get('q');
      
            $entities =  $em->getRepository('App:Facture')->findEntitiesByString($requestString);
      
            if(!$entities) {
                $result['entities']['error'] = "search not found";
            } else {
                $result['entities'] = $this->getRealEntities($entities);
            }
      
            return new Response(json_encode($result));
        }
      
        public function getRealEntities($entities){
      
            foreach ($entities as $entity){
                $realEntities[$entity->getId()] = $entity->getNomUser();
            }
      
            return $realEntities;
        }

}

templates/facture/_delete_form.html.twig
<form method="post" action="{{ path('facture_delete', {'id': facture.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ facture.id) }}">
    <button class="btn">Delete</button>
</form>

templates/facture/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_errors(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/facture/edit.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Edit Facture{% endblock %}

{% block body %}
    <h1>Edit Facture</h1>

    {{ include('facture/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('facture_index') }}">back to list</a>

    {{ include('facture/_delete_form.html.twig') }}
{% endblock %}

templates/facture/index.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Facture index{% endblock %}

{% block body %}

    <h1>Facture index</h1>

<h2>Search :</h2>

            <div class="sidebar-search">

                <div class="input-group custom-search-form">

                    <input type="text" id="search" class="form-control" placeholder="Search here">
                </div>
                <!-- /input-group -->
            </div>
            <ul class="nav" id="side-menu">
                <li>
                    <a href="#"> Factures<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level" id="entitiesNav">
                    </ul>
                </li>
            </ul><br><br><br><br>

            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

            <script type="text/javascript">
                jQuery(document).ready(function() {
                    var searchRequest = null;
                    $("#search").keyup(function() {
                        var minlength = 1;
                        var that = this;
                        var value = $(this).val();
                        var entitySelector = $("#entitiesNav").html('');
                        if (value.length >= minlength ) {
                            if (searchRequest != null)
                                searchRequest.abort();
                            searchRequest = $.ajax({
                                type: "GET",
                                url: "{{ path('ajax_search') }}",
                                data: {
                                    'q' : value
                                },
                                dataType: "text",
                                success: function(msg){
                                    //we need to check if the value is the same
                                    if (value===$(that).val()) {
                                        var result = JSON.parse(msg);
                                        $.each(result, function(key, arr) {
                                            $.each(arr, function(id, value) {
                                                if (key === 'factures') {
                                                    if (id !== 'error') {
                                                        console.log(value[1]);
                                                    } else {
                                                        entitySelector.append('<li class="errorLi">'+value+'</li>');
                                                    }
                                                }
                                            });
                                        });
                                    }
                                }
                            });
                        }
                    });
                });
            </script>



    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_user</th>
                <th>Prenom_user</th>
                <th>Matricule</th>
                <th>Code</th>
                <th>Prix</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for facture in factures %}
            <tr>
                <td>{{ facture.id }}</td>
                <td>{{ facture.nomUser }}</td>
                <td>{{ facture.prenomUser }}</td>
                <td>{{ facture.matricule }}</td>
                <td>{{ facture.code }}</td>
                <td>{{ facture.prix }}</td>
                <td>{{ facture.dateDebut ? facture.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ facture.dateFin ? facture.dateFin|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('facture_show', {'id': facture.id}) }}">show</a>
                    <a href="{{ path('facture_edit', {'id': facture.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
            <div class="navigation">
            {{ knp_pagination_render(factures) }}
        </div>
                        <a href="{{ path('facture_new') }}">Add</a>

{% endblock %}

templates/facture/new.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}New Facture{% endblock %}

{% block body %}
    <h1>Create new Facture</h1>

    {{ include('facture/_form.html.twig') }}

    <a href="{{ path('facture_index') }}">back to list</a>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/61a940ea51498030cd3bd197/1fluib5ah';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
{% endblock %}

templates/facture/pdf.html.twig
    <h1>Facture index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_user</th>
                <th>Prenom_user</th>
                <th>Matricule</th>
                <th>Code</th>
                <th>Prix</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
            </tr>
        </thead>
        <tbody>
        {% for facture in factures %}
            <tr>
                <td>{{ facture.id }}</td>
                <td>{{ facture.nomUser }}</td>
                <td>{{ facture.prenomUser }}</td>
                <td>{{ facture.matricule }}</td>
                <td>{{ facture.code }}</td>
                <td>{{ facture.prix }}</td>
                <td>{{ facture.dateDebut ? facture.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ facture.dateFin ? facture.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

templates/facture/show.html.twig
{% extends 'base-front.html.twig' %}

{% block title %}Facture{% endblock %}

{% block body %}
    <h1>Facture</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ facture.id }}</td>
            </tr>
            <tr>
                <th>Nom_user</th>
                <td>{{ facture.nomUser }}</td>
            </tr>
            <tr>
                <th>Prenom_user</th>
                <td>{{ facture.prenomUser }}</td>
            </tr>
            <tr>
                <th>Matricule</th>
                <td>{{ facture.matricule }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ facture.code }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ facture.prix }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ facture.dateDebut ? facture.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ facture.dateFin ? facture.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('facture_index') }}">back to list</a>

    <a href="{{ path('facture_edit', {'id': facture.id}) }}">edit</a>
    <a href="{{ path('pdf') }}">pdf</a>
    {{ include('facture/_delete_form.html.twig') }}
{% endblock %}